# --- Metadata ----------------------------------------------------------------
metadata:
  name: Train Models w/ SMOTE for Class Imbalance
  description: >
    This is a configuration file for training machine learning models for
    network intrusion detection, using SMOTE for class imbalance.
  date_created: 2026-03-02


# --- Models -----------------------------------------------------------
models: 
  random_forest:
    module: sklearn.ensemble
    class: RandomForestClassifier
    hyperparameters:
      n_estimators: 100
      max_depth: 15
      min_samples_split: 10
      min_samples_leaf: 5
      max_features: 'sqrt'
      bootstrap: true
      random_state: 76
      n_jobs: 2
  xgboost:
    module: xgboost
    class: XGBClassifier
    hyperparameters:
      objective: 'multi:softprob'
      num_class: 11
      max_depth: 6
      learning_rate: 0.1
      n_estimators: 100
      subsample: 0.8
      colsample_bytree: 0.8
      min_child_weight: 5
      gamma: 0.1
      reg_alpha: 0.1
      reg_lambda: 1
      random_state: 76


# --- Pipeline ---------------------------------------------------------
pipeline:
  - step: Load data splits
    module: data.input_output
    function: load_data_splits
    params:
      directory: data/processed/
  
  - step: Train models
    module: models.train
    function: train_models
    params:
      models: models
      cv_k: 5
      cv_n_jobs: 4
      use_smote: true
      smote_max: 2500

  - step: Save results
    module: models.input_output
    function: save_results
    params:
      filename: results_smote.pkl
      directory: models/
